services : 

  rev_proxy :
    build : 
      context : ./nginx
      dockerfile : dockerfile.rev_proxy
    volumes : 
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports : 
      - 80:80
    restart : always
    depends_on : 
      - db
      - flask
      - adminer

    networks :
      - front
      - back

  db :
    env_file: .env
    image : mariadb
    restart : always
    environment :
      - MARIADB_ROOT_PASSWORD=${MOT_DE_PASSE}
      - MARIADB_DATABASE=tension_base
      - MARIADB_USER=${USER_APP}
      - MARIADB_PASSWORD=${MOT_DE_PASSE}
    volumes :
      - ./mariadb:/var/lib/mysql
    expose :
      - 3306
      - 33060
    networks : 
      - back

  adminer:
    env_file: .env 
    image : adminer
    restart : always
    depends_on :
      - db
    environment :
      - PMA_host=db
      - PMA_PASSWORD=${MOT_DE_PASSE}
    ports :
      - 9080:80
    networks :
      - front
      - back
  

  flask :
    build : 
      context : flask 
      dockerfile : dockerfile.flask
    restart : always
    depends_on : 
      - db
      
    volumes : 
      - ./index2.html:/var/www/localhost/htdocs/index.html
    ports :
      - 8090:80
    
    networks :
      - front
      - back

  script :
    build :
      context : ./script
      dockerfile : dockerfile.script
    restart : always
    depends_on :
      - flask
      - db

    networks :
      - front
      - back

volumes :
  mysql :
networks : 
  front :
  back :