name: regulation_tension
services : 
  flask :
    container_name: server_flask
    build : 
      context : ./flask 
      dockerfile : dockerfile.flask
    restart : always
    volumes : 
      - ./flask/main.py:/app/main.py:ro
      - ./flask/templates:/app/templates:ro     #ro pour read only
      - ./flask/static:/app/static:ro3
    ports :
      - 5000:5000

  script :
    container_name: script
    privileged: true
    build :
      context : ./script
      dockerfile : dockerfile.script 
    restart : always
    volumes :
      # fchier pour le scrip principal
      - ./script/main.py:/usr/src/app/main.py:ro
      - ./script/data.py:/usr/src/app/data.py:ro
      - ./script/transmitting.py:/usr/src/app/transmitting.py:ro

      # Pour script pour la raspberry pi
      - ./script/raspberry/__init__.py:/usr/src/app/raspberry/__init__.py:ro
      - ./script/raspberry/infoPc.py:/usr/src/app/raspberry/infoPc.py:ro
      - ./script/raspberry/multimetre.py:/usr/src/app/raspberry/multimetre.py:ro
      - ./script/raspberry/lineGpio.py:/usr/src/app/raspberry/lineGpio.py:ro
      - ./script/raspberry/relay.py:/usr/src/app/raspberry/relay.py:ro
      
      # Pour script pour la dataBase prometheus
      - ./script/dataBase/__init__.py:/usr/src/app/dataBase/__init__.py:ro
      - ./script/dataBase/sensor.py:/usr/src/app/dataBase/sensor.py:ro
      - ./script/dataBase/prometheus.py:/usr/src/app/dataBase/prometheus.py:ro

      # Pour script pour les modes de fonctionnement
      - ./script/modes/__init__.py:/usr/src/app/modes/__init__.py:ro
      - ./script/modes/consommation.py:/usr/src/app/modes/consommation.py:ro
      - ./script/modes/manuel.py:/usr/src/app/modes/manuel.py:ro
      - ./script/modes/observer.py:/usr/src/app/modes/observer.py:ro
      - ./script/modes/protect.py:/usr/src/app/modes/protect.py:ro
      
      # pour les gpio sur la raspberry p
      - /dev/gpiochip0:/dev/gpiochip0:ro
      
      # Pour la lecture des infos sur la raspberry pi
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro
      - /usr/lib/arm-linux-gnueabihf/libvcos.so.0:/usr/lib/arm-linux-gnueabihf/libvcos.so.0:ro
      - /usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0:/usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0:ro
    ports:
      - "8000:8000"

  rev_proxy :
    container_name: rev_proxy
    build : 
      context : ./nginx
      dockerfile : dockerfile.rev_proxy
    volumes : 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports : 
      - 80:80
    restart : always
    depends_on : 
      - flask
      - script

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    user: root
    volumes:
      - ./prometheus/prometheus.yml:/workspace/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/workspace/prometheus.yml'
      - '--storage.tsdb.retention.size=20000MB'


  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    user: root
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

    depends_on:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
      GF_PATHS_DATA: "/var/lib/grafana"

volumes :
  prometheus :
  grafana :