name: regulation_tension
services : 
  flask :
    container_name: server_flask
    build : 
      context : ./flask 
      dockerfile : dockerfile.flask
    restart : always
    volumes : 
      - ./flask/main.py:/app/main.py:ro
      - ./flask/templates:/app/templates:ro     #ro pour read only
      - ./flask/static:/app/static:ro3
      - ./flask/batSettings.json:/app/batSettings.json
    ports :
      - 5000:5000

  script :
    container_name: script
    privileged: true
    build :
      context : ./script
      dockerfile : dockerfile.script 
    restart : always
    volumes :
      # fchier pour le script flask
      - ./script/main.py:/usr/src/app/main.py:ro
      - ./script/infoPc.py:/usr/src/app/infoPc.py:ro
      - ./script/sensor.py:/usr/src/app/sensor.py:ro
      - ./script/multimetre.py:/usr/src/app/multimetre.py:ro
      - ./script/lineGpio.py:/usr/src/app/lineGpio.py:ro
      - ./script/relayState.json:/usr/src/app/relayState.json

      # pour les gpio sur la raspberry p
      - /dev/gpiochip0:/dev/gpiochip0:ro
      
      # Pour la lecture des infos sur la raspberry pi
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro
      - /usr/lib/arm-linux-gnueabihf/libvcos.so.0:/usr/lib/arm-linux-gnueabihf/libvcos.so.0:ro
      - /usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0:/usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0:ro
    ports:
      - "8090:8000"


  rev_proxy :
    container_name: rev_proxy
    build : 
      context : ./nginx
      dockerfile : dockerfile.rev_proxy
    volumes : 
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports : 
      - 80:80
    restart : always
    depends_on : 
      - flask
      - script

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.33.5
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/workspace
      - ./prometheus/data:/opt/bitnami/prometheus/data*
    command:
      - '--config.file=/workspace/prometheus.yml'
    depends_on:
      - script
  

  grafana:
    container_name: grafana
    image: grafana/grafana:8.4.3
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/*
      - ./grafana/data:/var/lib/grafana/*
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"

volumes :
  prometheus :