#version: "0.2"
name: regulation_tension
services : 
  rev_proxy :
    container_name: rev_proxy
    build : 
      context : ./nginx
      dockerfile : dockerfile.rev_proxy
    volumes : 
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports : 
      - 80:80
    restart : always
    depends_on : 
      - flask
    networks:
      - front
      - back

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.33.5
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/workspace
    command:
      - '--config.file=/workspace/prometheus.yml'
    networks:
      - front
  
  grafana:
    container_name: grafana
    image: grafana/grafana:8.4.3
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana/*
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      

    depends_on:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    networks:
      - front

  flask :
    container_name: flask
    build : 
      context : flask 
      dockerfile : dockerfile.flask
    restart : always
    depends_on : 
      - prometheus
    volumes : 
      - ./flask/main.py:/app/main.py:ro
      - ./flask/templates:/app/templates:ro     #ro pour read only
      - ./flask/static:/app/static:ro
      

    ports :
      - 8090:5000
    
    networks :
      - front

  script :
    container_name: script
    privileged: true
    build :
      context : ./script
      dockerfile : dockerfile.script 
    restart : always
    depends_on :
      - flask

    volumes :
      - ./script/main.py:/usr/src/app/main.py:ro
      - ./script/infoPc.py:/usr/src/app/infoPc.py:ro
      - ./script/sensor.py:/usr/src/app/sensor.py:ro
      - /dev/gpiochip0:/dev/gpiochip0:ro

      # Pour la lecture des infos sur la raspberry pi
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro
      - /usr/lib/arm-linux-gnueabihf/libvcos.so.0:/usr/lib/arm-linux-gnueabihf/libvcos.so.0:ro
      - /usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0:/usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0:ro

    ports:
      - "8000:8000"   


    networks :
      - back

volumes :
  prometheus :
networks :
  front :
  back :
