FROM nginx:latest
RUN apt update -y && apt upgrade -y && apt install bash -y && apt clean && rm -rf /var/lib/apt/lists/*

COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/
CMD ["nginx", "-g", "daemon off;"]