version : 3.9


services : 

  rev_proxy :
    build : 
      context : nginx
      dockerfile : dockerfile.rev_proxy
    volumes : 
      - nginx/templates:/etc/nginx/templates
      - nginx/nginx.conf:/etc/nginx/nginx.conf
    ports : 
      - 80:80
    depends_on : 
      - db
      - flask
      - php_myadmin

    networks :
      - front
      - back

  db :
    image : mysql
    restart : always
    environnments :
      - MYSQL_ROOT_PASSWORD : 1234
      - MYSQL_DATABASE : tension_base
      - MYSQL_USER : flask
      - MYSQL_PASSWORD : password
    volumes :
      - mysql:/var/lib/mysql
    expose :
      - 3306
      - 33060

  php_myadmin:
    image : phpmyadmin
    restart : always
    depends_on :
      - db
    environnment :
      PMA_host : db
      PMA_PASSWORD : password #repris depuis fichier externe
    ports :
      - 9080:80
    networks :
      - front
      - back
  

  flask :
    build : 
      context : flask 
      dockerfile : dockerfile.flask
    restart: always
    secrets : 
      - password #repris de fichier externe
    depends_on : 
      - db
      - rev_proxy
      
    volumes : 
      - index2.html:/var/www/localhost/htdocs/index.html
    ports :
      - 8090:80
    
    network :
      - front
      - back

  script :
    build :
      context : script
      dockerfile : dockerfile.script
    restart : allways
    secrets : 
      - password
    depends_on :
      - flask
      - db

    networks :
      - front
      - back 