{
 "title": "Contrôleur batterie",
 "description": "Graphique pour le contrôle de l'état de la batteire",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mode",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    { "expr": "au_ob", "legendFormat": "Mode Observation" },
    { "expr": "au_co", "legendFormat": "Mode Consommation" },
    { "expr": "au_pr", "legendFormat": "Mode Protection" },
    { "expr": "au_ma", "legendFormat": "Mode Manuel" }
   ]
  },
  {
   "title": "Batterie Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bus_voltage_01", "legendFormat": "Tension de la Batterie" }
   ]
  },
  {
   "title": "Environnement ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "targets": [
    { "expr": "temperature", "legendFormat": "Température °C" },
    { "expr": "humidity", "legendFormat": "Humidité %" }
   ]
  },
  {
   "title": "Espace Disque utilisé",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_ussed", "legendFormat": "Espace disque utilisé" }
   ]
  },
  {
   "title": "RAM Utilisée ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ram_ussed", "legendFormat": "RAM utilisée" }
   ]
  },
  {
   "title": "Tensions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 16 },
   "targets": [
    { "expr": "psu_voltage_01", "legendFormat": "Tension Batterie" },
    { "expr": "psu_voltage_02", "legendFormat": "Tension de charge" },
    { "expr": "psu_voltage_03", "legendFormat": "Tension de consommation" }
   ]
  },
  {
   "title": "Puissances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 22 },
   "targets": [
    { "expr": "current_02", "legendFormat": "Courant circuit de charge" },
    { "expr": "current_03", "legendFormat": "Consommation des équipement " }
   ]
  }
 ]
}