{
 "title": "Raspberry pi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tension CPU",
   "type": "gauge",
   "description": "Tension du CPU de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_volt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Température CPU",
   "type": "gauge",
   "description": "Température du CPU de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Utilisation CPU",
   "type": "gauge",
   "description": "Utilisation du CPU de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tension CPU",
   "type": "timeseries",
   "description": "Tension du CPU de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "cpu_volt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Température CPU",
   "type": "timeseries",
   "description": "Température du CPU de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "cpu_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Utilisation CPU",
   "type": "timeseries",
   "description": "Utilisation du CPU de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ram utilisé %",
   "type": "gauge",
   "description": "Ram utilisé % de la Raspberry pi",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "porcent_ram_ussed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ram total",
   "type": "timeseries",
   "description": "Ram total de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    { "expr": "ram_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ram libre",
   "type": "timeseries",
   "description": "Ram libre de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "targets": [
    { "expr": "ram_free", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ram utilisé",
   "type": "timeseries",
   "description": "Ram utilisé de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    { "expr": "ram_ussed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disque utilisé %",
   "type": "gauge",
   "description": "Ram utilisé % de la Raspberry pi",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "porcent_disk_ussed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disque total",
   "type": "timeseries",
   "description": "Disque total de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "targets": [
    { "expr": "disk_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disque libre",
   "type": "timeseries",
   "description": "Disque libre de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "targets": [
    { "expr": "disk_free", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disque utilisé",
   "type": "timeseries",
   "description": "Disque utilisé de la Raspberry pi",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "targets": [
    { "expr": "disk_ussed", "legendFormat": "__auto" }
   ]
  }
 ]
}