FROM python:latest
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir- -r requirements.txt && apt update && apt install --no_cache bash && apt install
COPY . .
CMD [ " python", "./main.py"]