FROM python:3.9-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN apt update && apt install bash && apt install -y bash && \
pip install --upgrade pip && \
pip install --no-cache-dir -r requirements.txt && \
apt clean && rm -rf /var/lib/apt/lists/*

COPY . .
CMD ["python3", "./main.py"]


