FROM python:3.13-slim

WORKDIR /usr/src/app

COPY requirements.txt ./


RUN apt update && pip install --upgrade pip && \
pip install --no-cache-dir -r requirements.txt && \
apt clean && rm -rf /var/lib/apt/lists/*


CMD ["python3", "main.py"]