FROM python:3.13-alpine

COPY requirements.txt ./

# installation de Flask et Waitress
RUN pip install --upgrade pip && \
pip install --no-cache-dir -r requirements.txt

# création d'un utilisateur guichri pour ne pas être root ensuite
RUN adduser -D guichri

# création d'un dossier /app avec l'utilisateur guichri comme propriétaire
RUN mkdir /app && chown guichri /app

# bascule sur l'utilisateur guichri
USER guichri

# démarrage du serveur en dernière étape
CMD ["python3", "/app/main.py"]
